### ISSUE TITLE
Enable Grammar Checker add-on to work with the CardBook add-on

### ISSUE THREAD

**Issue by ovari** [nuald/thb-gramchecker#12]
Please enable your Grammar Checker add-on to work with the CardBook add-on
https://addons.thunderbird.net/thunderbird/addon/cardbook/

Cards in the CardBook add-on have a "Notes" tab which could benefit from your Grammar Checker add-on. A mock-up of a Card in CardBook is shown below with your Grammar Checker button.
![image](https://user-images.githubusercontent.com/17465872/46509455-2105c800-c886-11e8-8984-c950af114e9d.png)

Similar functionality to the Compose Message window showing your Grammar Checker button.
![image](https://user-images.githubusercontent.com/17465872/46509538-a4271e00-c886-11e8-98d3-ac138e7bbae9.png)

[CardBook add-on Notes Toolbar](https://gitlab.com/CardBook/CardBook/issues/354) issue has been created.

What do you think?

Thank you

**Comment by nuald** [comment]
I'm willing to accept and test any PR, however I'm not doing the active development of the addon as it requires a lot of reverse engineering and source code analysis and I don't have time for that. So while it's a totally valid request, I can't promise any soon resolution, sorry.
