### ISSUE TITLE
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/

### ISSUE THREAD

**Issue by ovari** [nuald/thb-gramchecker#14]
### ATN in Hungarian
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/

**Title**
from
`Grammar Checker`
to
`Nyelvtan-ellenőrzes (Grammar Checker)`

**Description**
from:
`Checks grammar using LanguageTool.`
to:
`Nyelvtan-ellenőrzes a LanguageTool segítségével.`

**Image captions**
* from:
`Screenshot of Grammar Check at work`
to:
`Nyelvtan ellenőrzése`
* from:
`GrammarChecker preferences`
to:
`Nyelvtan-ellenőrzes beállítások`

Thank you

**Comment by nuald** [comment]
Done

**Comment by ovari** [comment]
Thank you.

Did you receive a notification about:
https://github.com/nuald/thb-gramchecker/pull/13#issuecomment-432366773
?
