### ISSUE TITLE
thunderbirdOverlay.xul - vbox

### ISSUE THREAD

**Issue by ndvbd** [nuald/thb-gramchecker#25]
Where can we find documentation about this vbox property? I couldn't find it anywhere.
is there a way to place the div on the right side of the screen instead of on the bottom?
is there a way to debug the dom window and see this div inside vbox?

**Comment by nuald** [comment]
vbox documentation is a part of obsolete XUL documentation: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/vbox

I'm not sure how TB render things and works with layout now, but I guess it's possible to put `hbox` inside `appcontent` (the plugin operates ids, not tags, so it may work).

As for the debugging - TB has the development tools installed, but it could be quite confusing. For your particular question, you can use Inspect tool, but please don't forget to switch to the required frame: https://stackoverflow.com/questions/63289427/using-developer-tools-on-a-thuderbird-add-on-dialog

**Comment by ndvbd** [comment]
Thanks @nuald ,
1. I tried changing the 'vbox' to 'hbox' in appcontent, but nothing changed. It is still at the bottom of the compose email screen instead of on the side.
2. When you say 'obsolete', do you mean that there is a better/newer way to write this extension, without .XUL?
