### ISSUE TITLE
Thunderbird 78 Support

### ISSUE THREAD

**Issue by memarama** [nuald/thb-gramchecker#26]

**Comment by jh20001** [comment]
I do hope this one lives on with TB 78 :)

**Comment by ok1vaw** [comment]
I hope too, very useful add-on, and I am missing it very much. Is somebody working on porting it to the new version?

**Comment by gstlouisgit** [comment]
looking forward to this as well

**Comment by binarykitchen** [comment]
yes plleeeaaaaasseeeee

**Comment by cavemanr** [comment]
This add-on has to be continued. LanguageTool should be implemented in every Software ;).

**Comment by syrabo** [comment]
yes please

**Comment by Mannshoch** [comment]
ping @nuald ❤️

**Comment by RalfRoemling** [comment]
+1 from me
