### ISSUE TITLE
Error in console with my TB

### ISSUE THREAD

**Issue by ArfyFR** [nuald/thb-gramchecker#6]
My TB:52.1.0 (32 bits) on Windows 10 up to date

For me the extension stays in "Requestiong [fr]" and in console:

```
SyntaxError: The URI is malformed.  overlay.js:255
	grammarchecker._checkGrammar chrome://grammarchecker/content/overlay.js:255:13
	grammarchecker.onMenuItemCommand/< chrome://grammarchecker/content/overlay.js:290:17
	grammarchecker._checkGrammar/req.onreadystatechange chrome://grammarchecker/content/overlay.js:265:25
```

**Comment by nuald** [comment]
The requesting message should mention the server used, therefore it looks like the add-on preferences were not properly set up (it should be `Requesting http://localhost:8081 [fr]`). Please verify the add-on preferences (menu "Tools" -> "Addons", use the "Preferences" button for the addon).

By default, these two servers should be there (if not, just put the URLs there):

- http://localhost:8081 (the local one)
- https://languagetool.org/api (the public server)

To verify the plugin, you can use the public server, but due to privacy and performance issues it's strongly recommended to set up a local server.

**Comment by ArfyFR** [comment]
Thanks,

I just tried to uninstall (restart TB) it and reinstall it (+also restart TB) but now with option I have:
```
Erreur d’analyse XML : entité non définie
Emplacement : chrome://grammarchecker/content/options.xul
Numéro de ligne 40, Colonne 1 :<prefwindow id="grammarcheckerPreferences" xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" title="&prefwindow.title;">
^
```
Erm, where can I remove the unwanted, I suppose, preferences ?

**Comment by nuald** [comment]
I guess the problem is not with the preferences per se, but with the localization - I haven't tested the up-to-dated Thunderbird localization, it may have issues I haven't addressed yet. I'll take a look.

**Comment by nuald** [comment]
Unfortunately, I can't reproduce the issue. You may want to try change the options manually - maybe just deleting the old entries may help. Please locate the `%APPDATA%\Thunderbird\Profiles\<Profile Name>\extensions\prefs.js` file, and remove the lines having `extensions.grammarchecker.`, for example:

    user_pref("extensions.grammarchecker.mothertongue", "fr");

**Comment by ArfyFR** [comment]
Hi,

- I closed TB
- Removed all grammarchecker from %APPDATA%\Thunderbird\Profiles\<Profile Name>\prefs.js (and not %APPDATA%\Thunderbird\Profiles\<Profile Name>\**extensions**\prefs.js)
- Restarted TB

Tried, but same error: see [IMG](https://c1.staticflickr.com/5/4183/33583487254_b63f8d058e_o.jpg)

I checked in about:config all is "by default" now cf [screenshot](https://c1.staticflickr.com/5/4183/34265931202_6e548690b7_o.jpg)

**Comment by nuald** [comment]
I've noticed the options which do not belong to the addon - looks like some other addon influences this one. I'd recommend the following:

- try to disable other addons, and verify does it help - if does, locate the exact addon and let me know, I'll try to play with it to find the solution;
- if disabling doesn't help, please provide me the installed addon list, I'll try to reproduce it locally.

**Comment by ArfyFR** [comment]
Hi, not @home at the moment to check.
Which options did you notice ?

**Comment by nuald** [comment]
Native options for the grammarchecker addon are:

- langpref;
- mothertongue;
- urlpref1;
- urlpref2.

Other options which are not declared and used by the addon, and presented in the screenshot are:

- bDictClassic;
- bDictClassicReform;
- bDictModern;
- bDictReform;
- sGCOptions;
- sTFOptions.

**Comment by ArfyFR** [comment]
Ok found.  Removed grammalecte extension and now it works again.
(was https://addons.mozilla.org/fr/thunderbird/addon/grammalecte-fr-thunderbird/ I tested as Gramchecker didn't work anymore)
