### ISSUE TITLE
Problem using grammar checker with Thunderbird 60

### ISSUE THREAD

**Issue by chrisgns** [nuald/thb-gramchecker#8]
An error occurred executing the cmd_grammar command: [Exception... "[JavaScript Error: "xhr is undefined" {file: "chrome://grammarchecker/content/overlay.js" line: 214}]'[JavaScript Error: "xhr is undefined" {file: "chrome://grammarchecker/content/overlay.js" line: 214}]' when calling method: [nsIControllerCommand::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://global/content/globalOverlay.js :: goDoCommand :: line 84"  data: yes]

**Comment by ProfRon** [comment]
I'm seeing the exact same error. Started with TBird 60.0. 

For what it's worth, I also cannot change the "preferences" -- or rather, every time I pull up the "preferences" pop-up for this extension, all the preferences appear to be blank.  As such, I don't know if the preferences are correctly set. I had the extension disabled at first, after installing TBird 60. After re-enabling it, I wanted to double-check that the prefs were OK, but can't see what they are.

By the way -- the prefs pop-up is no longer correctly formatted (all 4 preferences appear in one line, not under each other anymore).

I'm using TB 60.0, Grammar Checker 0.8, installed from addons.thunderbird.net, under Arch Linux.
I checked that language tool is running locally (and reachable at port 8081) ... it is. Seems to be OK.

**Comment by nuald** [comment]
The version has been approved: https://addons.thunderbird.net/en-US/thunderbird/addon/grammar-checker/

**Comment by ProfRon** [comment]
Just a quick note to say (1) Yes, it works now and (2) Thanks!

**Comment by ovari** [comment]
Created pull request https://github.com/nuald/thb-gramchecker/pull/9 so that your add-on will work for the life of the Thunderbird 60 ESR.

You merged it very quickly too as it is merged before this could be written. Well done.
